# -*- coding: utf-8 -*-

def bibli():
    runfile('C:/Users/StageCO2/manip/air_atm.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/animate.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/azote.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/config_oxy.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/conv_capt_pression.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/decode_frame_GPS.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/decode_frame_GPS.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/decode_frame_licor.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/decode_frame_ox.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/decode_frame_temp.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/eau_mers.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/ecriture.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/enchain_cycle.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/etal_bas.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/etal_haut.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/etal_moy.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/evac_piege_froid.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/fichier_moyennage.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/init_lecture_fichier_brut.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/initialisation_moxa.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/send_lecture_seule.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/send_rs232.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/nouv_fichier_ecriture.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/nouv_fichier.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/ouverture_nouv_fichier_brut.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/get_jour.py', wdir='C:/Users/StageCO2/manip')
    runfile('C:/Users/StageCO2/manip/get_mois.py', wdir='C:/Users/StageCO2/manip')


